/*
 * This file is generated by jOOQ.
 */
package org.liman.olymp_task_setter.subject_schema.tables;


import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.liman.olymp_task_setter.subject_schema.Activity;
import org.liman.olymp_task_setter.subject_schema.Keys;
import org.liman.olymp_task_setter.subject_schema.tables.records.ActivitiesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Activities extends TableImpl<ActivitiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>activity.activities</code>
     */
    public static final Activities ACTIVITIES = new Activities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActivitiesRecord> getRecordType() {
        return ActivitiesRecord.class;
    }

    /**
     * The column <code>activity.activities.id</code>.
     */
    public final TableField<ActivitiesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>activity.activities.name</code>.
     */
    public final TableField<ActivitiesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private Activities(Name alias, Table<ActivitiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Activities(Name alias, Table<ActivitiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>activity.activities</code> table reference
     */
    public Activities(String alias) {
        this(DSL.name(alias), ACTIVITIES);
    }

    /**
     * Create an aliased <code>activity.activities</code> table reference
     */
    public Activities(Name alias) {
        this(alias, ACTIVITIES);
    }

    /**
     * Create a <code>activity.activities</code> table reference
     */
    public Activities() {
        this(DSL.name("activities"), null);
    }

    public <O extends Record> Activities(Table<O> child, ForeignKey<O, ActivitiesRecord> key) {
        super(child, key, ACTIVITIES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Activity.ACTIVITY;
    }

    @Override
    public UniqueKey<ActivitiesRecord> getPrimaryKey() {
        return Keys.ACTIVITIES_PKEY;
    }

    @Override
    public Activities as(String alias) {
        return new Activities(DSL.name(alias), this);
    }

    @Override
    public Activities as(Name alias) {
        return new Activities(alias, this);
    }

    @Override
    public Activities as(Table<?> alias) {
        return new Activities(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Activities rename(String name) {
        return new Activities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Activities rename(Name name) {
        return new Activities(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Activities rename(Table<?> name) {
        return new Activities(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super UUID, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super UUID, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
