/*
 * This file is generated by jOOQ.
 */
package org.liman.olymp_task_setter.activity_schema;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.liman.olymp_task_setter.activity_schema.tables.Activities;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Activity extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>activity</code>
     */
    public static final Activity ACTIVITY = new Activity();

    /**
     * The table <code>activity.activities</code>.
     */
    public final Activities ACTIVITIES = Activities.ACTIVITIES;

    /**
     * No further instances allowed
     */
    private Activity() {
        super("activity", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Activities.ACTIVITIES
        );
    }
}
