/*
 * This file is generated by jOOQ.
 */
package org.liman.olymp_task_setter.subject_schema;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.liman.olymp_task_setter.subject_schema.tables.Activities;
import org.liman.olymp_task_setter.subject_schema.tables.records.ActivitiesRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * activity.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ActivitiesRecord> ACTIVITIES_PKEY = Internal.createUniqueKey(Activities.ACTIVITIES, DSL.name("activities_pkey"), new TableField[] { Activities.ACTIVITIES.ID }, true);
}
