/*
 * This file is generated by jOOQ.
 */
package org.liman.olymp_task_setter.subject_schema;


import org.liman.olymp_task_setter.subject_schema.tables.Activities;


/**
 * Convenience access to all tables in activity.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>activity.activities</code>.
     */
    public static final Activities ACTIVITIES = Activities.ACTIVITIES;
}
